default: &local_defaults
  adapter: postgresql
  host: localhost
  encoding: utf8
  username: postgres
  pool: 5

development:
  <<: *local_defaults
  database: my_three_favorite_development

test:
  <<: *local_defaults
  database: my_three_favorite_test
